// components/poster/index.js
Component({
  properties: {
    paper: {
      type: Object,
      value: null
    }
  },

  data: {
    showCanvas: false,
    canvasWidth: 750,
    canvasHeight: 1200,
    generating: false,
    imageUrl: ''
  },

  methods: {
    /**
     * 生成海报
     */
    async generatePoster() {
      if (!this.data.paper) {
        wx.showToast({
          title: '请先提供论文数据',
          icon: 'none'
        });
        return;
      }

      this.setData({ generating: true, showCanvas: true });

      try {
        const query = this.createSelectorQuery();
        const canvasNode = await new Promise((resolve) => {
          query.select('#poster-canvas')
            .fields({ node: true, size: true })
            .exec((res) => resolve(res[0]));
        });

        if (!canvasNode) {
          throw new Error('Canvas 节点获取失败');
        }

        const canvas = canvasNode.node;
        const ctx = canvas.getContext('2d');

        // 设置 Canvas 尺寸（考虑像素比）
        const dpr = wx.getSystemInfoSync().pixelRatio || 1;
        canvas.width = this.data.canvasWidth * dpr;
        canvas.height = this.data.canvasHeight * dpr;
        ctx.scale(dpr, dpr);

        // 绘制海报
        await this.drawPoster(ctx, this.data.canvasWidth, this.data.canvasHeight);

        // 导出图片
        const filePath = await new Promise((resolve, reject) => {
          canvas.toTempFilePath({
            success: (res) => resolve(res.tempFilePath),
            fail: reject
          });
        });

        this.setData({
          imageUrl: filePath,
          showCanvas: false
        });

        wx.showToast({
          title: '海报生成成功',
          icon: 'success'
        });

      } catch (error) {
        console.error('生成海报失败:', error);
        wx.showToast({
          title: '生成失败: ' + error.message,
          icon: 'none'
        });
      } finally {
        this.setData({ generating: false });
      }
    },

    /**
     * 绘制海报内容
     */
    async drawPoster(ctx, width, height) {
      const { paper } = this.data;

      // 清空画布
      ctx.clearRect(0, 0, width, height);

      // 绘制背景
      ctx.fillStyle = '#ffffff';
      ctx.fillRect(0, 0, width, height);

      // 绘制顶部装饰条
      const gradient = ctx.createLinearGradient(0, 0, width, 0);
      gradient.addColorStop(0, '#1e3a5f');
      gradient.addColorStop(1, '#2d5a87');
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, width, 16);

      // 绘制期刊名称
      ctx.fillStyle = '#1e3a5f';
      ctx.font = 'bold 48px Times New Roman';
      ctx.textAlign = 'center';
      ctx.fillText('NATURE', width / 2, 120);

      ctx.fillStyle = '#6b7280';
      ctx.font = '24px sans-serif';
      ctx.fillText('Absurdity Edition', width / 2, 160);

      // 绘制分区标签
      const zoneColors = {
        'SSS一区': '#dc2626',
        'S一区': '#ea580c',
        'A一区': '#16a34a',
        'B区': '#2563eb',
        'C区': '#6b7280'
      };

      const zoneColor = zoneColors[paper.zone] || '#6b7280';
      const zoneText = paper.zone || 'C区';

      // 分区标签背景
      const badgeX = width / 2 - 100;
      const badgeY = 200;
      ctx.fillStyle = zoneColor;
      this.roundRect(ctx, badgeX, badgeY, 200, 50, 25);
      ctx.fill();

      // 分区标签文字
      ctx.fillStyle = '#ffffff';
      ctx.font = 'bold 28px sans-serif';
      ctx.fillText(zoneText, width / 2, badgeY + 35);

      // 绘制标题（自动换行）
      ctx.fillStyle = '#1a1a1a';
      ctx.font = '36px sans-serif';
      ctx.textAlign = 'left';
      this.drawTextWrapped(ctx, paper.title, 60, 400, 630, 50);

      // 绘制 AIF 分数
      ctx.fillStyle = '#1e3a5f';
      ctx.font = 'bold 60px sans-serif';
      ctx.textAlign = 'left';
      ctx.fillText('AIF', 60, 660);

      ctx.fillStyle = '#dc2626';
      ctx.font = 'bold 100px sans-serif';
      ctx.fillText((paper.aif?.total || 0).toString(), 60, 780);

      // 绘制底部信息
      ctx.fillStyle = '#6b7280';
      ctx.font = '24px sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText(`DOI: ${paper.metadata?.doi || ''}`, width / 2, 1050);

      ctx.fillStyle = '#9ca3af';
      ctx.font = '20px sans-serif';
      ctx.fillText('Generated by AI · For Entertainment Only', width / 2, 1100);

      // 绘制底部警告
      ctx.fillStyle = '#f3f4f6';
      const qrY = 1150;
      this.roundRect(ctx, width / 2 - 100, qrY, 200, 40, 8);
      ctx.fill();

      ctx.fillStyle = '#6b7280';
      ctx.font = '18px sans-serif';
      ctx.fillText('长按识别阅读全文', width / 2, qrY + 28);
    },

    /**
     * 绘制圆角矩形
     */
    roundRect(ctx, x, y, width, height, radius) {
      ctx.beginPath();
      ctx.moveTo(x + radius, y);
      ctx.lineTo(x + width - radius, y);
      ctx.arcTo(x + width, y, x + width, y + radius, radius);
      ctx.lineTo(x + width, y + height - radius);
      ctx.arcTo(x + width, y + height, x + width - radius, y + height, radius);
      ctx.lineTo(x + radius, y + height);
      ctx.arcTo(x, y + height, x, y + height - radius, radius);
      ctx.lineTo(x, y + radius);
      ctx.arcTo(x, y, x + radius, y, radius);
      ctx.closePath();
    },

    /**
     * 绘制自动换行的文本
     */
    drawTextWrapped(ctx, text, x, y, maxWidth, lineHeight) {
      const chars = text.split('');
      let line = '';
      let currentY = y;

      for (let i = 0; i < chars.length; i++) {
        const testLine = line + chars[i];
        const metrics = ctx.measureText(testLine);
        const testWidth = metrics.width;

        if (testWidth > maxWidth && i > 0) {
          ctx.fillText(line, x, currentY);
          line = chars[i];
          currentY += lineHeight;
        } else {
          line = testLine;
        }
      }
      ctx.fillText(line, x, currentY);
    },

    /**
     * 保存海报到相册
     */
    savePoster() {
      if (!this.data.imageUrl) {
        return;
      }

      wx.saveImageToPhotosAlbum({
        filePath: this.data.imageUrl,
        success: () => {
          wx.showToast({
            title: '已保存到相册',
            icon: 'success'
          });
        },
        fail: (error) => {
          if (error.errMsg.includes('auth deny')) {
            wx.showModal({
              title: '提示',
              content: '需要授权访问相册',
              success: (res) => {
                if (res.confirm) {
                  wx.openSetting();
                }
              }
            });
          } else {
            wx.showToast({
              title: '保存失败',
              icon: 'none'
            });
          }
        }
      });
    }
  }
});
